export const SET_LANGUAGES = 'SET_LANGUAGES'

export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILED = 'AUTH_FAILED'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_RESET = 'AUTH_RESET'

export const NEW_OFFER_DETAILS = 'NEW_OFFER_DETAILS'
export const NEW_OFFER_CONTENT = 'NEW_OFFER_CONTENT'