export const SET_LANGUAGES = 'SET_LANGUAGES'

export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILED = 'AUTH_FAILED'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_RESET = 'AUTH_RESET'
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS'
export const AUTH_USER_NOT_VERIFIED = 'AUTH_USER_NOT_VERIFIED'
export const AUTH_VERIFIED_RESET = 'AUTH_VERIFIED_RESET'

export const NEW_OFFER_DETAILS = 'NEW_OFFER_DETAILS'
export const NEW_OFFER_CONTENT = 'NEW_OFFER_CONTENT'

export const OFFER_SAVE_START = 'OFFER_SAVE_START'
export const OFFER_SAVE_SUCCESS = 'OFFER_SAVE_SUCCESS'
export const OFFER_SAVE_FAILED = 'OFFER_SAVE_FAILED'
export const OFFER_SAVE_RESET = 'OFFER_SAVE_RESET'
export const OFFER_SAVE_CLEAR_ERROR = 'OFFER_SAVE_CLEAR_ERROR'

export const FETCH_OFFERS_SUCCESS = 'FETCH_OFFERS_SUCCESS'
export const FETCH_OFFERS_FAILED = 'FETCH_OFFERS_FAILED'